### ISSUE TITLE
Add answers

### ISSUE THREAD

**Issue by adamjohnson** [scottaohara/accessibility_interview_questions#10]
These questions are great, but I feel like everyone would benefit from including answers with each question.

You might be able to accomplish this via the `<details>` and `<summary>` tags, like so:

<details>
    <summary>This is a question?</summary>
    <p>
        And this is the answer.
    </p>
</details>

[Syntax example in a README](https://raw.githubusercontent.com/scottaohara/a11y_styled_form_controls/master/README.md)

Yay? Nay?

**Comment by scottaohara** [comment]
Heya @adamjohnson 

I think that might be a good progression for the project at some point, but was definitely left out intentionally.  Some of these questions can be pretty straight forward, while others could consist of entire articles worth of content.  

Definitely something to think about...but if I / others did answer them, I would likely link out to posts that would provide the answers, of which there could even be a few different links per each.

Also, did you just link to another one of my projects to show me how I could add details/summary element to my readme?  ;)

**Comment by adamjohnson** [comment]
Ten-four. I am going to close this issue for now. If/when you circle back and add answers, this issue will be here to reopen. 

  > Also, did you just link to another one of my projects to show me how I could add details/summary element to my readme? ;)

Yup, did that intentionally. I couldn't find docs for it and figured others might find how to do it useful.

**Comment by scottaohara** [comment]
Appreciated @adamjohnson.

That said, I'm wondering if there might be an opportunity here to create some articles for [the accessibility project](https://a11yproject.com) based on some of the questions in this repo.

@ericwbailey waddyathinkmang?

**Comment by ericwbailey** [comment]
Ooh, I like that idea. 

@adamjohnson, if you're interested, The A11Y Project would love to post an article derived from one of these questions if you're feeling adventurous!

**Comment by scottaohara** [comment]
I’d say under categories that exist on the a11yproject already.
