### ISSUE TITLE
ARIA questions

### ISSUE THREAD

**Issue by robfentress** [scottaohara/accessibility_interview_questions#11]
Can you name an ARIA role, property, or state that is not currently supported by the latest version of at least one popular assistive technology?
What other assistive technologies can be affected by use of ARIA, aside from screen readers?  How?
Can you give an example of a pattern described in the ARIA Authoring Practices that would be problematic for smart phone users?  In what ways?

**Comment by scottaohara** [comment]
for the three questions you have here:

1. I think the first one is a bit too advanced / obscure for what I was trying to go for here.  but maybe there's a new section that could be spun up for specific technical questions.  I'll have to think on that.
2. I like this one.  we should add it.
3. This one could be generalized a bit. e.g. "Name a type of component that becomes problematic on primarily touch devices?"  hmm...

**Comment by robfentress** [comment]
As regards number three, I guess there are two separate issues.  One is the fact that certain interaction patterns don't work on touch screen devices or small form factors, and the other is that some ARIA roles, states, and properties are not communicated to those using mobile operating system screen readers.  I had the [ARIA design patterns - touch UA/AT gap analysis](https://docs.google.com/spreadsheets/d/1gN9oRZPdrJxLDNtT6nVO4fn7E7sn1061L9Xl3__slZ4/edit#gid=0) in mind when writing this one.

**Comment by robfentress** [comment]
As regards number one, I get it.  I guess it depends on the position the person is applying for.  If they can't name at least one, then it suggests to me that they probably haven't done enough testing with assistive technologies to be a good fit for some at least _some_ positions.

**Comment by scottaohara** [comment]
note: question 2 added via #15
