### ISSUE TITLE
Interpersonal skills questions

### ISSUE THREAD

**Issue by robfentress** [scottaohara/accessibility_interview_questions#12]
Can you give an example of where you were able to convince a developer or administrator who was resistant to your advice regarding accessibility to change their mind?  What strategies did you use?

**Comment by scottaohara** [comment]
i like this one, but think it needs to be reworded a bit to be a bit more concise.

**Comment by aviquid** [comment]
I wanted to ask a question related to accessibility and @robfentress had asked a similar one. On the same track another question - 
How would you convince your Manager to allocate some funds to do an accessibility external audit?

**Comment by scottaohara** [comment]
i like this.  @aviquid you want to make a PR with that?  probably would go under general for now.

**Comment by aviquid** [comment]
Sure @scottaohara. Will create one.
