### ISSUE TITLE
Question use of word 'inappropriately'

### ISSUE THREAD

**Issue by LaurenceRLewis** [scottaohara/accessibility_interview_questions#18]
Thank you for compiling this list. I am having an interview next week and it is great prep.

In the question _Describe an instance of inappropriately using ARIA attributes,_ inappropriate is generally more a reference of human behaviour.

Would this question be better posed as '_Describe an instance of incorrectly used, or invalid, ARIA attributes._

If there is a reason inappropriately is used please let me know how the word should be interpreted. :-)

**Comment by scottaohara** [comment]
ARIA doesn't apply itself to code, humans do, often inappropriately "not suitable or proper in the circumstances."

simplest example is `<button role=button>`.  Not incorrect as the role is in alignment with the element's intended role. But it is needless, inappropriate, and likely a display of the human not actually understanding what they're doing.
