### ISSUE TITLE
Accessible Materials Specialist

### ISSUE THREAD

**Issue by bakkenb** [scottaohara/accessibility_interview_questions#22]
How about adding a section on interview questions for an Accessible Materials Specialist. Questions around making sure that Word, Excel, PPT files are accessible and structured with good design. Proper tagging of PDFs, etc. Things that are not web pages or web applications, but are downloaded or distributed electronically.

**Comment by scottaohara** [comment]
have some questions that could be added?

**Comment by bakkenb** [comment]
Actually don't. I was looking for some as we are getting ready to post the position and the link to this repo came up. Good questions here already, just not specific to a materials responsibility.

**Comment by ericwbailey** [comment]
I'll take a shot at a basic first pass 👀
