### ISSUE TITLE
Questions that may need re-writing for clarification.

### ISSUE THREAD

**Issue by Decrepidos** [scottaohara/accessibility_interview_questions#7]
Observations when reading the list of questions and my thoughts for two of them.

If I was asked the following questions I would require more information to answer.

_Describe what someone would use heading tags for?_
I would ask if this question referred to the `<header>` element as related to banner, or, level headings as in `<h1>`, `<h2>` etc.

_What are your thoughts on modifying the way screen readers announce certain content?_
This would depend on the definition of 'certain content' and whether it is related to when content is announced as opposed to 'the way'. :-)

**Comment by scottaohara** [comment]
Hi @Decrepidos thanks for the feedback.

Per your first query, the question is not about `header`s, but heading levels.  It's probably a good idea to better surface that as your comment has reminded me there there may be some people don't know the difference. (which in and of itself might lead to an answer that would help decide whether to hire this particular person or not).

Per your second query, I think your response would actually be a good initial response for a candidate.  The question is meant to surface whether a candidate has a position on modifying the DOM to change how a screen reader announces text on a page.  for example adding aria-labels to alter number announcements.

I'd be more than happy to accept an alternate wording for such a question from you, if you'd like to contribute one :)  (and any other pertinent questions you think should be added!)

Thanks again

**Comment by Decrepidos** [comment]
I would update the question:

What are your thoughts on modifying the way screen readers announce certain content?

To

What is your understanding of the ‘’accessible name computation’ and how it affects modifying the way screen readers announce certain content?

**Comment by scottaohara** [comment]
Thank you!

**Comment by scottaohara** [comment]
going to reopen this as a reminder to update the second question's wording

**Comment by Decrepidos** [comment]
No worries sorry for closing.

**Comment by Decrepidos** [comment]
I do a lot of accessibility audits at work and often find issues with ARIA missing required children or parent attributes. So I thought  question along the lines of : can you name an ARIA attribute that requires either a child/parent relationship or a paring role.
